service:
  name: ${env:STAGE}-${self:provider.region}-${env:APP_NAME}
plugins:
  - serverless-dotenv-plugin
custom:
  dotenv:
    basePath: environments/
    exclude: # By default dotenv will add the env to your functions
      - ACCESS_KEY_ID
      - SECRET_ACCESS_KEY
provider:
  name: aws
  region: "us-east-1"
  stage: ${env:STAGE, 'dev'}
  stackName: ${self:service.name}-acm-stack

resources:
  Resources:
    ApiGatewayCert:
      Type: AWS::CertificateManager::Certificate
      Properties:
        DomainName: ${env:API_DOMAIN}
        DomainValidationOptions:
          - DomainName: ${env:API_DOMAIN}
            ValidationDomain: ${env:API_DOMAIN}
        ValidationMethod: DNS

  Outputs:
    ApiGatewayCert:
      Value:
        Ref: ApiGatewayCert
      Export:
        Name: ${self:service.name}-ApiGatewayCert
