Resources:
  ElasticLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      LoadBalancerName: ${env.APP_NAME}-alb
      SecurityGroups:
        - Ref: AlbSg
      Subnets: 
        - Ref: WebSubAz1
        - Ref: WebSubAz2
      Instances:
        - Ref: ec2instance01
      Listeners:
        - LoadBalancerPort: '3306'
          InstancePort: '8080'
          InstanceProtocol: HTTP
          Protocol: HTTP
      AccessLoggingPolicy:
        EmitInterval: '60'
        Enabled: 'False'
        S3BucketName: elb-logs
        S3BucketPrefix: ELB
      HealthCheck:
        Target: TCP:8080
        HealthyThreshold: '5'
        UnhealthyThreshold: '10'
        Interval: '30'
        Timeout: '5'
      ConnectionDrainingPolicy:
        Enabled: true
        Timeout: '60'
      Tags:
        - Key: Name
          Value: ELB_Name