  Resources:
    #Identity
    Identity:
      Type: "AWS::DynamoDB::Table"
      Properties:
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: email
            AttributeType: S
          - AttributeName: phoneNumber
            AttributeType: S
        TableName: ${env:DB_TABLE_NAME}
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: byEmail
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
          - IndexName: byPhoneNumber
            KeySchema:
              - AttributeName: phoneNumber
                KeyType: HASH
            Projection:
              ProjectionType: ALL
         

