service:
  name: ${env:STAGE}-${self:provider.region}-${env:APP_NAME}
plugins:
  - serverless-dotenv-plugin
custom:
  dotenv:
    basePath: ../../environments/
    exclude: # By default dotenv will add the env to your functions
      - ACCESS_KEY_ID
      - SECRET_ACCESS_KEY 
provider:
  name: aws
  region: ${env:REGION, 'eu-west-1'}
  stage: ${env:STAGE, 'dev'}
  stackName: ${self:service.name}-route53-stack

resources:
  Resources:
       #Consumer Webiste
    IdentityWebsite:
      Type: AWS::Route53::RecordSetGroup
      Properties:
        HostedZoneId: ${env:HOSTED_ZONE_ID}
        RecordSets:
          - Name: ${env:UI_DOMAIN}
            Type: A
            AliasTarget:
              HostedZoneId: Z2FDTNDATAQYW2 #Special AWS id required for this to work
              DNSName: ${file(./cognito/cognito.js):customDomainCf}
          - Name: ${env:UI_DOMAIN}
            Type: AAAA
            AliasTarget:
              HostedZoneId: Z2FDTNDATAQYW2 #Special AWS id required for this to work
              DNSName: ${file(./cognito/cognito.js):customDomainCf}


    